// Generated by GitHub Copilot
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  readonly profile = {
    name: 'Jutharat Thaisamrong',
    title: 'Application Support Engineer',
    location: 'Bangkok, Thailand',
    phone: '063-658-8539',
    email: 'juthor@gmail.com'
  };

  readonly summary = 'Application Support Engineer with 5 years of experience in enterprise system implementation, production support, troubleshooting, and web application development within multinational environments. Skilled in root cause analysis, SQL troubleshooting, API integration, deployment, and cross-system investigation. Experienced in implementing and supporting enterprise web applications for large-scale organizations, debugging backend/frontend issues, and collaborating with cross-functional teams to resolve complex production incidents. Strong technical background in C# .NET, Angular, SQL Server, PostgreSQL, and REST APIs with hands-on experience in both software development and production support.';

  readonly skillGroups: ReadonlyArray<{ label: string; items: string[] }> = [
    { label: 'Programming Languages', items: ['C#', '.NET', 'Java', 'SQL', 'JavaScript', 'TypeScript'] },
    { label: 'Frontend Technologies', items: ['Angular'] },
    { label: 'Backend & API', items: ['ASP.NET', 'REST API', 'API Integration', 'Postman'] },
    { label: 'Database', items: ['SQL Server', 'PostgreSQL'] },
    { label: 'Tools & Platforms', items: ['Visual Studio', 'Visual Studio Code', 'GitHub', 'GitLab', 'DBeaver', 'Postman'] },
    {
      label: 'Core Competencies',
      items: [
        'Production Support',
        'Root Cause Analysis',
        'System Troubleshooting',
        'Incident Investigation',
        'Deployment',
        'Debugging',
        'QA Testing',
        'Log Analysis',
        'Cross-functional Collaboration',
        'Application Maintenance',
        'Enterprise System Implementation'
      ]
    }
  ];

  readonly experience: ReadonlyArray<{
    role: string;
    officialTitle?: string;
    company: string;
    location: string;
    period: string;
    responsibilities: string[];
    clientWork?: { heading: string; items: string[] };
    achievements: string[];
  }> = [
    {
      role: 'Application Support Engineer',
      officialTitle: 'Business Architecture Analyst',
      company: 'IT One Co., Ltd.',
      location: 'Bangkok, Thailand',
      period: '2021 - Present',
      responsibilities: [
        'Supported and maintained enterprise web applications in production environments.',
        'Investigated and analyzed system issues reported by users, including transaction failures, incorrect statuses, and application errors.',
        'Performed root cause analysis by reviewing application logs, SQL queries, API responses, and backend/frontend code.',
        'Coordinated with cross-functional teams to troubleshoot issues across integrated systems and services.',
        'Developed and modified backend functionalities using C# .NET and frontend components using Angular.',
        'Performed debugging and issue analysis for production and non-production environments.',
        'Executed deployments across local, QA, and production environments.',
        'Conducted testing and validation before production releases.',
        'Utilized Postman to test and validate REST APIs.',
        'Managed source code and deployment workflows using GitHub and GitLab.',
        'Provided technical support and communicated issue resolutions to end users and stakeholders.',
        'Participated in on-call support activities for production incidents when required.'
      ],
      clientWork: {
        heading: 'Enterprise System Implementation & Client Experience',
        items: [
          'Implemented and supported the CUPA system for enterprise clients including SCGP and Kasikornbank.',
          'Participated in deployment, configuration, testing, troubleshooting, and post-production support activities during system implementation phases.',
          'Collaborated closely with clients and cross-functional teams to ensure successful system go-live and issue resolution.',
          'Provided production support and technical investigation for hospital-sector applications, including Siriraj Hospital.',
          'Worked with PostgreSQL databases for data investigation and troubleshooting activities.',
          'Coordinated support activities related to SAP-integrated systems.'
        ]
      },
      achievements: [
        'Successfully handled 20-30 production support cases monthly.',
        'Reduced issue resolution time through effective troubleshooting and root cause analysis.',
        'Supported mission-critical enterprise applications used by multiple organizations and business users.',
        'Improved system investigation efficiency across integrated applications and services.',
        'Delivered application fixes and enhancements with minimal production impact.'
      ]
    }
  ];

  readonly education: ReadonlyArray<{ degree: string; school: string; year: string }> = [
    {
      degree: 'Bachelor of Science in Computer Science',
      school: 'Mahasarakham University',
      year: '2012'
    }
  ];

  readonly languages: ReadonlyArray<{ name: string; level: string }> = [
    { name: 'Thai', level: 'Native' },
    { name: 'English', level: 'Intermediate (B1+), currently improving technical communication and business discussion skills' }
  ];

  readonly additional: ReadonlyArray<string> = [
    'Experienced in multinational working environments.',
    'Strong analytical and problem-solving skills.',
    'Able to work in both technical support and development roles.',
    'Experienced in handling production incidents and communicating with end users and technical teams.'
  ];

  print(): void {
    window.print();
  }
}